# Generated by Django 5.2 on 2025-08-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('skill', models.CharField(choices=[('Py', 'python'), ('Java', 'Java')], max_length=10)),
                ('Age', models.IntegerField()),
                ('Email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
